require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Api::V1::Users::AbilitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Api::V1::Users::Ability. As you add validations to Api::V1::Users::Ability, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::Users::AbilitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all api_v1_users_abilities as @api_v1_users_abilities" do
      ability = Api::V1::Users::Ability.create! valid_attributes
      get :index, {}, valid_session
      assigns(:api_v1_users_abilities).should eq([ability])
    end
  end

  describe "GET show" do
    it "assigns the requested api_v1 as @api_v1" do
      ability = Api::V1::Users::Ability.create! valid_attributes
      get :show, {:id => ability.to_param}, valid_session
      assigns(:api_v1).should eq(ability)
    end
  end

  describe "GET new" do
    it "assigns a new api_v1 as @api_v1" do
      get :new, {}, valid_session
      assigns(:api_v1).should be_a_new(Api::V1::Users::Ability)
    end
  end

  describe "GET edit" do
    it "assigns the requested api_v1 as @api_v1" do
      ability = Api::V1::Users::Ability.create! valid_attributes
      get :edit, {:id => ability.to_param}, valid_session
      assigns(:api_v1).should eq(ability)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Api::V1::Users::Ability" do
        expect {
          post :create, {:api_v1 => valid_attributes}, valid_session
        }.to change(Api::V1::Users::Ability, :count).by(1)
      end

      it "assigns a newly created api_v1 as @api_v1" do
        post :create, {:api_v1 => valid_attributes}, valid_session
        assigns(:api_v1).should be_a(Api::V1::Users::Ability)
        assigns(:api_v1).should be_persisted
      end

      it "redirects to the created api_v1" do
        post :create, {:api_v1 => valid_attributes}, valid_session
        response.should redirect_to(Api::V1::Users::Ability.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved api_v1 as @api_v1" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Users::Ability.any_instance.stub(:save).and_return(false)
        post :create, {:api_v1 => {  }}, valid_session
        assigns(:api_v1).should be_a_new(Api::V1::Users::Ability)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Users::Ability.any_instance.stub(:save).and_return(false)
        post :create, {:api_v1 => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested api_v1" do
        ability = Api::V1::Users::Ability.create! valid_attributes
        # Assuming there are no other api_v1_users_abilities in the database, this
        # specifies that the Api::V1::Users::Ability created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Api::V1::Users::Ability.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => ability.to_param, :api_v1 => { "these" => "params" }}, valid_session
      end

      it "assigns the requested api_v1 as @api_v1" do
        ability = Api::V1::Users::Ability.create! valid_attributes
        put :update, {:id => ability.to_param, :api_v1 => valid_attributes}, valid_session
        assigns(:api_v1).should eq(ability)
      end

      it "redirects to the api_v1" do
        ability = Api::V1::Users::Ability.create! valid_attributes
        put :update, {:id => ability.to_param, :api_v1 => valid_attributes}, valid_session
        response.should redirect_to(ability)
      end
    end

    describe "with invalid params" do
      it "assigns the api_v1 as @api_v1" do
        ability = Api::V1::Users::Ability.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Users::Ability.any_instance.stub(:save).and_return(false)
        put :update, {:id => ability.to_param, :api_v1 => {  }}, valid_session
        assigns(:api_v1).should eq(ability)
      end

      it "re-renders the 'edit' template" do
        ability = Api::V1::Users::Ability.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Users::Ability.any_instance.stub(:save).and_return(false)
        put :update, {:id => ability.to_param, :api_v1 => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested api_v1" do
      ability = Api::V1::Users::Ability.create! valid_attributes
      expect {
        delete :destroy, {:id => ability.to_param}, valid_session
      }.to change(Api::V1::Users::Ability, :count).by(-1)
    end

    it "redirects to the api_v1_users_abilities list" do
      ability = Api::V1::Users::Ability.create! valid_attributes
      delete :destroy, {:id => ability.to_param}, valid_session
      response.should redirect_to(api_v1_users_abilities_url)
    end
  end

end
