development:
  bypass_api_key_verification: false
  bypass_token_verification: false
  catch_exceptions: false
  super_user: false
test:
  bypass_api_key_verification: false
  bypass_token_verification: false
  catch_exceptions: true
production:
  bypass_api_key_verification: false
  bypass_token_verification: false
  catch_exceptions: true
