development:
  S3_KEY: 'AKIAISHIKVJWE3NYHUZQ'
  S3_SECRET: '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'
  S3_REGION: 'us-west-2'
  S3_BUCKET_NAME: physiotec-images-dev
  S3_ASSET_URL: 'https://s3-us-west-2.amazonaws.com'

test:
  S3_KEY: 'AKIAISHIKVJWE3NYHUZQ'
  S3_SECRET: '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'
  S3_REGION: 'us-west-2'
  S3_BUCKET_NAME: physiotec-images-dev
  S3_ASSET_URL:

production:
  S3_KEY: 'AKIAISHIKVJWE3NYHUZQ'
  S3_SECRET: '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'
  S3_REGION: 'us-west-2'
  S3_BUCKET_NAME: physiotec-images-prod
  S3_ASSET_URL:
